// <auto-generated />
using System;
using ConsoleTestNetCore.Containers.InDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ConsoleTestNetCore.Migrations
{
    [DbContext(typeof(HotelServicesDbContext))]
    [Migration("20190224181318_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("HotelServicesNetCore.Order", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Cost");

                    b.Property<bool>("IsPaid");

                    b.Property<DateTime>("OrderDate");

                    b.Property<string>("ServiceId");

                    b.Property<long>("Units");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("HotelServicesNetCore.Role", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = "552993ba-055a-4749-ac17-6e77c3b62a74",
                            Name = "Клиент"
                        },
                        new
                        {
                            Id = "fe9bd704-cbaf-41b1-b691-fb5d8c7985f2",
                            Name = "Администратор"
                        },
                        new
                        {
                            Id = "416073d0-3a17-4cbc-9035-5f3e0a7d0586",
                            Name = "Управляющий"
                        });
                });

            modelBuilder.Entity("HotelServicesNetCore.ServiceInfo", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("CostPerUnit");

                    b.Property<string>("Measurement");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("ServiceInfos");

                    b.HasData(
                        new
                        {
                            Id = "fdf04ac2-c523-4e25-884c-e4e7b112a2ab",
                            CostPerUnit = 1000m,
                            Measurement = "час.",
                            Name = "Спа"
                        },
                        new
                        {
                            Id = "1b8fed43-9237-4998-b25d-063b23f00672",
                            CostPerUnit = 2000m,
                            Measurement = "час",
                            Name = "Бильярд восьмёрка"
                        },
                        new
                        {
                            Id = "19334466-5e9e-4f5d-bccd-710364f42ee0",
                            CostPerUnit = 2000m,
                            Measurement = "час",
                            Name = "Бильярд девятка"
                        },
                        new
                        {
                            Id = "95984817-6bbd-440c-aece-78b272512990",
                            CostPerUnit = 2000m,
                            Measurement = "час",
                            Name = "Русский бильярд"
                        });
                });

            modelBuilder.Entity("HotelServicesNetCore.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Fio");

                    b.Property<string>("Login");

                    b.Property<string>("Password");

                    b.Property<string>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "b136278e-d453-4485-babf-9db66eb4ebcd",
                            Fio = "Петров П.П",
                            Login = "petr",
                            Password = "11111",
                            RoleId = "552993ba-055a-4749-ac17-6e77c3b62a74"
                        },
                        new
                        {
                            Id = "bd727a6a-ed86-4cfe-a5fb-37cad1313466",
                            Fio = "Смирнов П.П",
                            Login = "smr",
                            Password = "22222",
                            RoleId = "fe9bd704-cbaf-41b1-b691-fb5d8c7985f2"
                        },
                        new
                        {
                            Id = "1d1b0758-62d7-493f-818b-294ed87d2f90",
                            Fio = "Симонов П.П",
                            Login = "simon",
                            Password = "33333",
                            RoleId = "416073d0-3a17-4cbc-9035-5f3e0a7d0586"
                        },
                        new
                        {
                            Id = "c5374844-9455-481f-8a40-f067686a4703",
                            Fio = "Иванов П.П",
                            Login = "iva",
                            Password = "44444",
                            RoleId = "552993ba-055a-4749-ac17-6e77c3b62a74"
                        },
                        new
                        {
                            Id = "c245085f-30b5-4a40-bc2c-99ee812348c5",
                            Fio = "Сидоров П.П",
                            Login = "sidor",
                            Password = "55555",
                            RoleId = "552993ba-055a-4749-ac17-6e77c3b62a74"
                        });
                });

            modelBuilder.Entity("HotelServicesNetCore.Order", b =>
                {
                    b.HasOne("HotelServicesNetCore.ServiceInfo", "Service")
                        .WithOne("Order")
                        .HasForeignKey("HotelServicesNetCore.Order", "ServiceId");

                    b.HasOne("HotelServicesNetCore.User", "Client")
                        .WithOne("Order")
                        .HasForeignKey("HotelServicesNetCore.Order", "UserId");
                });

            modelBuilder.Entity("HotelServicesNetCore.User", b =>
                {
                    b.HasOne("HotelServicesNetCore.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");
                });
#pragma warning restore 612, 618
        }
    }
}
