// <auto-generated />
using System;
using ConsoleTestNetCore.Containers.InDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ConsoleTestNetCore.Migrations
{
    [DbContext(typeof(HotelServicesDbContext))]
    [Migration("20190225154341_Orders_Services_One_To_Many")]
    partial class Orders_Services_One_To_Many
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("HotelServicesNetCore.Order", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Cost");

                    b.Property<bool>("IsPaid");

                    b.Property<DateTime>("OrderDate");

                    b.Property<string>("ServiceId");

                    b.Property<long>("Units");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("HotelServicesNetCore.Role", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = "6f9c37b6-5ba0-4582-a1bc-708642c1079f",
                            Name = "Клиент"
                        },
                        new
                        {
                            Id = "a6615a24-570b-4bf1-980f-e69ab6957add",
                            Name = "Администратор"
                        },
                        new
                        {
                            Id = "ffe5ca75-81ed-432c-85b7-20a8a3d7245b",
                            Name = "Управляющий"
                        });
                });

            modelBuilder.Entity("HotelServicesNetCore.ServiceInfo", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("CostPerUnit");

                    b.Property<string>("Measurement");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("ServiceInfos");

                    b.HasData(
                        new
                        {
                            Id = "1e75571d-a33c-4a56-9c33-e8c047fcacca",
                            CostPerUnit = 1000m,
                            Measurement = "час.",
                            Name = "Спа"
                        },
                        new
                        {
                            Id = "d2a9100e-843d-40f2-873d-38793fa644d3",
                            CostPerUnit = 2000m,
                            Measurement = "час",
                            Name = "Бильярд восьмёрка"
                        },
                        new
                        {
                            Id = "fe326a82-cdf5-436e-aac8-b117bcef0d67",
                            CostPerUnit = 2000m,
                            Measurement = "час",
                            Name = "Бильярд девятка"
                        },
                        new
                        {
                            Id = "e870c5a2-e990-4429-8940-c128a5a65b32",
                            CostPerUnit = 2000m,
                            Measurement = "час",
                            Name = "Русский бильярд"
                        });
                });

            modelBuilder.Entity("HotelServicesNetCore.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Fio");

                    b.Property<string>("Login");

                    b.Property<string>("Password");

                    b.Property<string>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "04b24114-b976-428d-bd8e-b89abd21046e",
                            Fio = "Петров П.П",
                            Login = "petr",
                            Password = "11111",
                            RoleId = "6f9c37b6-5ba0-4582-a1bc-708642c1079f"
                        },
                        new
                        {
                            Id = "aee0a7ca-cdb9-4dcc-8cfb-ca5e7b510481",
                            Fio = "Смирнов П.П",
                            Login = "smr",
                            Password = "22222",
                            RoleId = "a6615a24-570b-4bf1-980f-e69ab6957add"
                        },
                        new
                        {
                            Id = "35216458-5801-404e-a4f6-98d376562cea",
                            Fio = "Симонов П.П",
                            Login = "simon",
                            Password = "33333",
                            RoleId = "ffe5ca75-81ed-432c-85b7-20a8a3d7245b"
                        },
                        new
                        {
                            Id = "2957934c-ac2b-4036-9c4a-c3b196e02dc6",
                            Fio = "Иванов П.П",
                            Login = "iva",
                            Password = "44444",
                            RoleId = "6f9c37b6-5ba0-4582-a1bc-708642c1079f"
                        },
                        new
                        {
                            Id = "e187d3ed-8912-4042-a380-012d90bf81d5",
                            Fio = "Сидоров П.П",
                            Login = "sidor",
                            Password = "55555",
                            RoleId = "6f9c37b6-5ba0-4582-a1bc-708642c1079f"
                        });
                });

            modelBuilder.Entity("HotelServicesNetCore.Order", b =>
                {
                    b.HasOne("HotelServicesNetCore.ServiceInfo", "Service")
                        .WithMany("Orders")
                        .HasForeignKey("ServiceId");

                    b.HasOne("HotelServicesNetCore.User", "User")
                        .WithOne("Order")
                        .HasForeignKey("HotelServicesNetCore.Order", "UserId");
                });

            modelBuilder.Entity("HotelServicesNetCore.User", b =>
                {
                    b.HasOne("HotelServicesNetCore.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");
                });
#pragma warning restore 612, 618
        }
    }
}
