// <auto-generated />
using System;
using ConsoleTestNetCore.Containers.InDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ConsoleTestNetCore.Migrations
{
    [DbContext(typeof(HotelServicesDbContext))]
    partial class HotelServicesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("HotelServicesNetCore.Order", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Cost");

                    b.Property<bool>("IsPaid");

                    b.Property<DateTime>("OrderDate");

                    b.Property<string>("ServiceId");

                    b.Property<long>("Units");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("HotelServicesNetCore.Role", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = "3d1ece96-f442-4933-8904-222c416658f9",
                            Name = "Клиент"
                        },
                        new
                        {
                            Id = "e1a08eb9-7542-4b57-a778-07ce1953655a",
                            Name = "Администратор"
                        },
                        new
                        {
                            Id = "adc7c2d2-603a-4291-971b-d8da557c8648",
                            Name = "Управляющий"
                        });
                });

            modelBuilder.Entity("HotelServicesNetCore.ServiceInfo", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("CostPerUnit");

                    b.Property<bool>("IsDeprecated");

                    b.Property<string>("Measurement");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("ServiceInfos");

                    b.HasData(
                        new
                        {
                            Id = "3cce7817-37c3-4db6-94c7-3614fa874e0d",
                            CostPerUnit = 1000m,
                            IsDeprecated = false,
                            Measurement = "час.",
                            Name = "Спа"
                        },
                        new
                        {
                            Id = "1ed5091c-71e9-42bc-90dc-e8d0879a9e04",
                            CostPerUnit = 2000m,
                            IsDeprecated = false,
                            Measurement = "час",
                            Name = "Бильярд восьмёрка"
                        },
                        new
                        {
                            Id = "d911383f-3861-4bce-be08-df7b6cd5e9c0",
                            CostPerUnit = 2000m,
                            IsDeprecated = false,
                            Measurement = "час",
                            Name = "Бильярд девятка"
                        },
                        new
                        {
                            Id = "466e0082-6ebb-4cd7-aa75-ec2bc6749384",
                            CostPerUnit = 2000m,
                            IsDeprecated = false,
                            Measurement = "час",
                            Name = "Русский бильярд"
                        });
                });

            modelBuilder.Entity("HotelServicesNetCore.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Fio");

                    b.Property<string>("Login");

                    b.Property<string>("Password");

                    b.Property<string>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "d70eb863-3e7c-4b12-b5f1-3c2811e76ac6",
                            Fio = "Петров П.П",
                            Login = "petr",
                            Password = "11111",
                            RoleId = "3d1ece96-f442-4933-8904-222c416658f9"
                        },
                        new
                        {
                            Id = "6e82273d-a3e1-47c2-b698-97b3c24aa695",
                            Fio = "Смирнов П.П",
                            Login = "smr",
                            Password = "22222",
                            RoleId = "e1a08eb9-7542-4b57-a778-07ce1953655a"
                        },
                        new
                        {
                            Id = "424532fa-955e-4989-9795-7083217657f9",
                            Fio = "Симонов П.П",
                            Login = "simon",
                            Password = "33333",
                            RoleId = "adc7c2d2-603a-4291-971b-d8da557c8648"
                        },
                        new
                        {
                            Id = "e1fef2d1-defe-4e68-8824-b12be008edf3",
                            Fio = "Иванов П.П",
                            Login = "iva",
                            Password = "44444",
                            RoleId = "3d1ece96-f442-4933-8904-222c416658f9"
                        },
                        new
                        {
                            Id = "d521b263-4117-4df4-9aff-e3b580248bf7",
                            Fio = "Сидоров П.П",
                            Login = "sidor",
                            Password = "55555",
                            RoleId = "3d1ece96-f442-4933-8904-222c416658f9"
                        });
                });

            modelBuilder.Entity("HotelServicesNetCore.Order", b =>
                {
                    b.HasOne("HotelServicesNetCore.ServiceInfo", "Service")
                        .WithMany("Orders")
                        .HasForeignKey("ServiceId");

                    b.HasOne("HotelServicesNetCore.User", "User")
                        .WithMany("Order")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("HotelServicesNetCore.User", b =>
                {
                    b.HasOne("HotelServicesNetCore.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");
                });
#pragma warning restore 612, 618
        }
    }
}
